baseURL = 'https://joaomedeiros.dev/'
languageCode = 'en-us'
title = 'João Medeiros'
theme = 'typo'
enableEmoji = true

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "João Medeiros' Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a Senior Software Engineer from Brazil, a specialist in Django and Python, with extensive experience in DevOps and databases. 
Initially focused on backend development, I am successfully transitioning into a fullstack role, expanding my expertise to include 
front-end technologies and delivering comprehensive solutions.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/joaormedeiros/"

[[params.social]]
name = "github"
url = "https://github.com/joaomedeiros95"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = true
repo = "joaomedeiros95/joaomedeiros.dev"
repoid = "R_kgDOMszgow"
category = "Announcements"
categoryid = "DIC_kwDOMszgo84CibMN"
mapping = "title"
theme = "transparent_dark"

[params.umami]
enable = true
websiteId = "3785be39-760f-4439-89d1-05ad217e5033"
jsLocation = "https://cloud.umami.is/script.js"